version: "3.8"
services:
  crablog:
    build: .
    ports:
        - 8000:8000
    hostname: crablog
    container_name: crablog
    env_file: ./crablog.env
    restart: unless-stopped
    volumes:
      - ./content:/app/content
